[project]
name = "collabshell"
version = "1.0.0"
description = "CollabShell: Client for Google Colab"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "flet>=0.85.3",
    "flet-ads>=0.85.0",
    "google-colab-cli>=0.6.0",
    "rich>=15.0.0",
]

[tool.flet]
org = "ng.kiri"
product = "CollabShell"
build_number = 1

[tool.flet.app]
path = "src"

[tool.flet.app.boot_screen]
show = true
message = "Initializing CollabShell..."

[tool.flet.android]
bundle_id = "ng.kiri.collabshell"
split_per_abi = true
min_sdk_version = 24
target_sdk_version = 35

[tool.flet.android.meta_data]
"com.google.android.gms.ads.APPLICATION_ID" = "ca-app-pub-5679949845754640~1261089274"

[tool.flet.android.manifest_application]
allowBackup = "false"

[tool.flet.android.permission]
"android.permission.INTERNET" = true
"android.permission.ACCESS_NETWORK_STATE" = true

[dependency-groups]
dev = [
    "ruff",
]
